//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "View Models" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using AdventureWorks.Client.Common.DataObjects;
using Microsoft.Extensions.DependencyInjection;
using System;
using Xomega.Framework.Views;

namespace AdventureWorks.Client.Common.ViewModels
{
    public partial class SalesOrderReasonViewModel : DetailsViewModel
    {
        public SalesOrderReasonObject MainObj => DetailsObject as SalesOrderReasonObject;

        public SalesOrderReasonViewModel(IServiceProvider sp) : base(sp)
        {
        }

        public override void Initialize()
        {
            base.Initialize();
            DetailsObject = ServiceProvider.GetService<SalesOrderReasonObject>();
        }
    }
}