//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "View Models" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using AdventureWorks.Client.Common.DataObjects;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Specialized;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework;
using Xomega.Framework.Views;

namespace AdventureWorks.Client.Common.ViewModels
{
    public partial class SalesOrderViewModel : DetailsViewModel
    {
        public SalesOrderObject MainObj => DetailsObject as SalesOrderObject;

        public SalesOrderViewModel(IServiceProvider sp) : base(sp)
        {
        }

        public override void Initialize()
        {
            base.Initialize();
            DetailsObject = ServiceProvider.GetService<SalesOrderObject>();
        }

        #region Link LinkDetailDetails

        public virtual NameValueCollection LinkDetailDetails_Params(DataRow row)
        {
            NameValueCollection query = new NameValueCollection()
            {
                { "SalesOrderDetailId", MainObj.DetailList.SalesOrderDetailIdProperty.GetStringValue(ValueFormat.EditString, row) },
                { ViewParams.Mode.Param, ViewParams.Mode.Popup },
                { ViewParams.QuerySource, "LinkDetailDetails" },
            };
            return query;
        }

        public virtual void LinkDetailDetails_Command(IView tgtView, IView curView, DataRow row)
        {
            NameValueCollection query = LinkDetailDetails_Params(row);
            ViewModel tgtModel = ServiceProvider.GetService<SalesOrderDetailViewModel>();
            NavigateTo(tgtModel, tgtView, query, this, curView);
        }

        public virtual async Task LinkDetailDetails_CommandAsync(IAsyncView tgtView, IAsyncView curView, DataRow row, CancellationToken token = default)
        {
            NameValueCollection query = LinkDetailDetails_Params(row);
            ViewModel tgtModel = ServiceProvider.GetService<SalesOrderDetailViewModel>();
            await NavigateToAsync(tgtModel, tgtView, query, this, curView, token);
        }

        public virtual bool LinkDetailDetails_Enabled(DataRow row)
        {
            return true;
        }
        #endregion

        #region Link LinkDetailNew

        public virtual NameValueCollection LinkDetailNew_Params()
        {
            NameValueCollection query = new NameValueCollection()
            {
                { ViewParams.Action.Param, ViewParams.Action.Create },
                { "SalesOrderId", MainObj.SalesOrderIdProperty.GetStringValue(ValueFormat.EditString) },
                { ViewParams.Mode.Param, ViewParams.Mode.Popup },
                { ViewParams.QuerySource, "LinkDetailNew" },
            };
            return query;
        }

        public virtual void LinkDetailNew_Command(IView tgtView, IView curView)
        {
            NameValueCollection query = LinkDetailNew_Params();
            ViewModel tgtModel = ServiceProvider.GetService<SalesOrderDetailViewModel>();
            NavigateTo(tgtModel, tgtView, query, this, curView);
        }

        public virtual async Task LinkDetailNew_CommandAsync(IAsyncView tgtView, IAsyncView curView, CancellationToken token = default)
        {
            NameValueCollection query = LinkDetailNew_Params();
            ViewModel tgtModel = ServiceProvider.GetService<SalesOrderDetailViewModel>();
            await NavigateToAsync(tgtModel, tgtView, query, this, curView, token);
        }

        public virtual bool LinkDetailNew_Enabled()
        {
            return !DetailsObject.IsNew;
        }
        #endregion

        #region Link LinkReasonDetails

        public virtual NameValueCollection LinkReasonDetails_Params(DataRow row)
        {
            NameValueCollection query = new NameValueCollection()
            {
                { "SalesOrderId", MainObj.SalesOrderIdProperty.GetStringValue(ValueFormat.EditString, row) },
                { "SalesReasonId", MainObj.ReasonList.SalesReasonIdProperty.GetStringValue(ValueFormat.EditString, row) },
                { ViewParams.Mode.Param, ViewParams.Mode.Popup },
                { ViewParams.QuerySource, "LinkReasonDetails" },
            };
            return query;
        }

        public virtual void LinkReasonDetails_Command(IView tgtView, IView curView, DataRow row)
        {
            NameValueCollection query = LinkReasonDetails_Params(row);
            ViewModel tgtModel = ServiceProvider.GetService<SalesOrderReasonViewModel>();
            NavigateTo(tgtModel, tgtView, query, this, curView);
        }

        public virtual async Task LinkReasonDetails_CommandAsync(IAsyncView tgtView, IAsyncView curView, DataRow row, CancellationToken token = default)
        {
            NameValueCollection query = LinkReasonDetails_Params(row);
            ViewModel tgtModel = ServiceProvider.GetService<SalesOrderReasonViewModel>();
            await NavigateToAsync(tgtModel, tgtView, query, this, curView, token);
        }

        public virtual bool LinkReasonDetails_Enabled(DataRow row)
        {
            return true;
        }
        #endregion

        #region Link LinkReasonNew

        public virtual NameValueCollection LinkReasonNew_Params()
        {
            NameValueCollection query = new NameValueCollection()
            {
                { ViewParams.Action.Param, ViewParams.Action.Create },
                { "SalesOrderId", MainObj.SalesOrderIdProperty.GetStringValue(ValueFormat.EditString) },
                { ViewParams.Mode.Param, ViewParams.Mode.Popup },
                { ViewParams.QuerySource, "LinkReasonNew" },
            };
            return query;
        }

        public virtual void LinkReasonNew_Command(IView tgtView, IView curView)
        {
            NameValueCollection query = LinkReasonNew_Params();
            ViewModel tgtModel = ServiceProvider.GetService<SalesOrderReasonViewModel>();
            NavigateTo(tgtModel, tgtView, query, this, curView);
        }

        public virtual async Task LinkReasonNew_CommandAsync(IAsyncView tgtView, IAsyncView curView, CancellationToken token = default)
        {
            NameValueCollection query = LinkReasonNew_Params();
            ViewModel tgtModel = ServiceProvider.GetService<SalesOrderReasonViewModel>();
            await NavigateToAsync(tgtModel, tgtView, query, this, curView, token);
        }

        public virtual bool LinkReasonNew_Enabled()
        {
            return !DetailsObject.IsNew;
        }
        #endregion
         
        #region Child selection event
          
        protected virtual void HandleSelection(object sender, ViewEvent e)
        {
            ViewModel child = sender as ViewModel;
        }

        protected override void OnChildEvent(object sender, ViewEvent e)
        {
            HandleSelection(sender, e);
            base.OnChildEvent(sender, e);
        }

        protected override async Task OnChildEventAsync(object sender, ViewEvent e, CancellationToken token = default)
        {
            HandleSelection(sender, e);
            await base.OnChildEventAsync(sender, e, token);
        }
        #endregion
    }
}