//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "REST Service Clients" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace AdventureWorks.Services.Common
{
    public static class RestClients
    {
        public static IServiceCollection AddRestClients(this IServiceCollection services)
        {
            services.TryAddScoped<IBusinessEntityService, BusinessEntityServiceClient>();
            services.TryAddScoped<ICustomerService, CustomerServiceClient>();
            services.TryAddScoped<IPasswordLoginService, PasswordLoginServiceClient>();
            services.TryAddScoped<IPersonService, PersonServiceClient>();
            services.TryAddScoped<IProductService, ProductServiceClient>();
            services.TryAddScoped<IProductSubcategoryService, ProductSubcategoryServiceClient>();
            services.TryAddScoped<ISalesOrderService, SalesOrderServiceClient>();
            services.TryAddScoped<ISalesPersonService, SalesPersonServiceClient>();
            services.TryAddScoped<ISalesReasonService, SalesReasonServiceClient>();
            services.TryAddScoped<ISalesTerritoryService, SalesTerritoryServiceClient>();
            services.TryAddScoped<IShipMethodService, ShipMethodServiceClient>();
            services.TryAddScoped<ISpecialOfferService, SpecialOfferServiceClient>();
            services.TryAddScoped<ISpecialOfferProductService, SpecialOfferProductServiceClient>();
            return services;
        }
    }
}