//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "REST Service Clients" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;

namespace AdventureWorks.Services.Common
{
    public static class RestClients
    {
        public static IServiceCollection AddRestClients(this IServiceCollection services)
        {
            services.AddScoped<ISalesOrderService, SalesOrderServiceClient>();
            return services;
        }
    }
}