//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Xomega Data Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using AdventureWorks.Services.Common;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework;
using Xomega.Framework.Properties;
using Xomega.Framework.Services;

namespace AdventureWorks.Client.Common.DataObjects
{
    public partial class LoginObject : DataObject
    {
        #region Constants

        public const string Password = "Password";
        public const string UserName = "UserName";

        #endregion

        #region Properties

        public TextProperty PasswordProperty { get; private set; }
        public TextProperty UserNameProperty { get; private set; }

        #endregion

        #region Construction

        public LoginObject()
        {
        }

        public LoginObject(IServiceProvider serviceProvider) : base(serviceProvider)
        {
        }

        protected override void Initialize()
        {
            UserNameProperty = new TextProperty(this, UserName)
            {
                Required = true,
                Size = 50,
            };
            PasswordProperty = new TextProperty(this, Password)
            {
                Required = true,
            };
        }

        #endregion

        #region CRUD Operations

        protected override async Task<ErrorList> DoSaveAsync(object options, CancellationToken token = default)
        {
            var res = NewErrorList();
            var output = await PasswordLogin_LoginAsync(options, token);
            res.MergeWith(output.Messages);
            return res;
        }

        #endregion

        #region Service Operations

        protected virtual async Task<Output<UserInfo>> PasswordLogin_LoginAsync(object options, CancellationToken token = default)
        {
            PasswordCredentials _credentials = ToDataContract<PasswordCredentials>(options);
            using (var s = ServiceProvider.CreateScope())
            {
                var output = await s.ServiceProvider.GetService<IPasswordLoginService>().LoginAsync(_credentials, token);

                return output;
            }
        }

        #endregion
    }
}