//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------


namespace AdventureWorks.Services.Common
{
    #region PasswordCredentials structure

    public class PasswordCredentials
    {

        public string UserName { get; set; }

        public string Password { get; set; }
    }
    #endregion

    #region UserInfo structure

    public class UserInfo
    {

        public string AuthenticationType { get; set; }

        public string UserName { get; set; }

        public int BusinessEntityId { get; set; }

        ///<summary>
        /// Primary type of person: SC = Store Contact, IN = Individual (retail) customer, SP = Sales person, EM = Employee (non-sales), VC = Vendor contact, GC = General contact
        ///</summary>
        public string PersonType { get; set; }

        ///<summary>
        /// First name of the person.
        ///</summary>
        public string FirstName { get; set; }

        ///<summary>
        /// Last name of the person.
        ///</summary>
        public string LastName { get; set; }

        public int? Store { get; set; }

        public int? Vendor { get; set; }
    }
    #endregion

}