//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    #region IPasswordLoginService interface

    public interface IPasswordLoginService
    {

        Task<Output<UserInfo>> LoginAsync(PasswordCredentials _credentials, CancellationToken token = default);

    }
    #endregion

}