//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    #region IShipMethodService interface

    ///<summary>
    /// Shipping company lookup table.
    ///</summary>
    public interface IShipMethodService
    {

        ///<summary>
        /// Reads a list of Ship Method objects based on the specified criteria.
        ///</summary>
        Task<Output<ICollection<ShipMethod_ReadListOutput>>> ReadListAsync(CancellationToken token = default);

    }
    #endregion

    #region ShipMethod_ReadListOutput structure

    ///<summary>
    /// The output structure of operation IShipMethodService.ReadListAsync.
    ///</summary>
    public class ShipMethod_ReadListOutput
    {
        
        public int ShipMethodId { get; set; }
        
        ///<summary>
        /// Shipping company name.
        ///</summary>
        public string Name { get; set; }
    }
    #endregion

}