//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    #region IBusinessEntityAddressService interface

    ///<summary>
    /// Cross-reference table mapping customers, vendors, and employees to their addresses.
    ///</summary>
    public interface IBusinessEntityAddressService
    {

        ///<summary>
        /// Reads a list of Business Entity Address objects based on the specified criteria.
        ///</summary>
        Task<Output<ICollection<BusinessEntityAddress_ReadListOutput>>> ReadListAsync(int _businessEntityId, CancellationToken token = default);

    }
    #endregion

    #region BusinessEntityAddress_ReadListOutput structure

    ///<summary>
    /// The output structure of operation IBusinessEntityAddressService.ReadListAsync.
    ///</summary>
    public class BusinessEntityAddress_ReadListOutput
    {
        
        public int AddressId { get; set; }
        
        public string AddressType { get; set; }
        
        public string AddressLine1 { get; set; }
        
        public string AddressLine2 { get; set; }
        
        public string City { get; set; }
        
        public string State { get; set; }
        
        public string PostalCode { get; set; }
        
        public string Country { get; set; }
    }
    #endregion

}