//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------


namespace AdventureWorks.Services.Common
{
    #region AddressKey structure

    ///<summary>
    /// Address key information
    ///</summary>
    public class AddressKey
    {
        
        public int AddressId { get; set; }
    }
    #endregion

    #region AddressInfo structure

    ///<summary>
    /// Full address information
    ///</summary>
    public class AddressInfo
    {
        
        ///<summary>
        /// First street address line.
        ///</summary>
        public string AddressLine1 { get; set; }
        
        ///<summary>
        /// Second street address line.
        ///</summary>
        public string AddressLine2 { get; set; }
        
        public string CityState { get; set; }
        
        ///<summary>
        /// Postal code for the street address.
        ///</summary>
        public string PostalCode { get; set; }
        
        public string Country { get; set; }
    }
    #endregion

}