//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "REST Service Clients" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.Options;
using System;
using System.Net.Http;
using System.Resources;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Client;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    public class PasswordLoginServiceClient : RestApiClient, IPasswordLoginService
    {
        public PasswordLoginServiceClient(IHttpClientFactory httpClientFactory, RestApiConfig apiConfig,
            IOptionsMonitor<JsonSerializerOptions> serializerOptions, ResourceManager resourceManager)
            : base(httpClientFactory, apiConfig, serializerOptions, resourceManager)
        {
        }

        /// <inheritdoc/>
        public virtual async Task<Output<UserInfo>> LoginAsync(PasswordCredentials _credentials, CancellationToken token = default)
        {
            await Task.CompletedTask;
            throw new NotSupportedException("Operation IPasswordLoginService.LoginAsync is not exposed via REST.");
        }
    }
}