//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Xomega Data Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;

namespace AdventureWorks.Client.Common.DataObjects
{
    public static class DataObjects
    {
        public static IServiceCollection AddDataObjects(this IServiceCollection services)
        {
            services.AddTransient<SalesOrderCriteria, SalesOrderCriteriaCustomized>();
            services.AddTransient<SalesOrderDetailList, SalesOrderDetailList>();
            services.AddTransient<SalesOrderDetailObject, SalesOrderDetailObject>();
            services.AddTransient<SalesOrderList, SalesOrderList>();
            services.AddTransient<SalesOrderObject, SalesOrderObject>();
            services.AddTransient<SalesOrderPaymentObject, SalesOrderPaymentObject>();
            services.AddTransient<SalesOrderSalesObject, SalesOrderSalesObjectCustomized>();
            return services;
        }
    }
}