//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "REST Service Clients" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.Options;
using System.Collections.Generic;
using System.Net.Http;
using System.Resources;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    ///<summary>
    /// Cross-reference table mapping products to special offer discounts.
    ///</summary>
    public class SpecialOfferProductServiceClient : HttpServiceClient, ISpecialOfferProductService
    {
        protected readonly JsonSerializerOptions SerializerOptions;

        public SpecialOfferProductServiceClient(HttpClient httpClient, IOptionsMonitor<JsonSerializerOptions> options, ResourceManager resourceManager)
            : base(httpClient, resourceManager)
        {
            SerializerOptions = options.CurrentValue;
        }

        /// <inheritdoc/>
        public virtual async Task<Output<ICollection<SpecialOfferProduct_ReadEnumOutput>>> ReadEnumAsync(int _productId, CancellationToken token = default)
        {
            HttpRequestMessage msg = new HttpRequestMessage(HttpMethod.Get, $"product/{ _productId }/special-offer");
            using (var resp = await Http.SendAsync(msg, HttpCompletionOption.ResponseHeadersRead, token))
            {
                var content = await ReadOutputContentAsync(resp);
                return await JsonSerializer.DeserializeAsync<Output<ICollection<SpecialOfferProduct_ReadEnumOutput>>>(content, SerializerOptions);
            }
        }
    }
}