//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Implementations" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Microsoft.Extensions.DependencyInjection;
using AdventureWorks.Services.Common;

namespace AdventureWorks.Services.Entities
{
    public static class ServiceImplementations
    {
        public static IServiceCollection AddServiceImplementations(this IServiceCollection services)
        {
            services.AddScoped<ISalesOrderService, SalesOrderService>();
            return services;
        }
    }
}