//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Blazor Views" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using Xomega.Framework.Blazor.Components;

namespace AdventureWorks.Client.Blazor.Common.Views
{
    public partial class MainMenu
    {
        private partial List<MenuItem> GeneratedItems() =>
        [
            new MenuItem()
            {
                ResourceKey = "Module_Sales_NavMenu",
                IconClass = "bi bi-columns",
                Items =
                [
                    new MenuItem()
                    {
                        ResourceKey = "CustomerListView_NavMenu",
                        IconClass = "bi bi-card-list",
                        Href = "CustomerListView",
                        Policy = "Sales"
                    },
                    new MenuItem()
                    {
                        ResourceKey = "SalesOrderView_NavMenu",
                        IconClass = "bi bi-pencil-square",
                        Href = "SalesOrderView?_action=create",
                        Policy = "Sales"
                    },
                    new MenuItem()
                    {
                        ResourceKey = "SalesOrderListView_NavMenu",
                        IconClass = "bi bi-card-list",
                        Href = "SalesOrderListView",
                        Policy = "Sales"
                    },
                ]
            },
        ];
    }
}