//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using AdventureWorks.Services.Common.Enumerations;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    #region ISalesOrderService interface

    ///<summary>
    /// General sales order information.
    ///</summary>
    public interface ISalesOrderService
    {

        ///<summary>
        /// Reads the values of a Sales Order object by its key.
        ///</summary>
        Task<Output<SalesOrder_ReadOutput>> ReadAsync(int _salesOrderId, CancellationToken token = default);

        ///<summary>
        /// Creates a new Sales Order object using the specified data.
        ///</summary>
        Task<Output<SalesOrder_CreateOutput>> CreateAsync(SalesOrder_CreateInput _data, CancellationToken token = default);

        ///<summary>
        /// Updates existing Sales Order object using the specified data.
        ///</summary>
        Task<Output> UpdateAsync(int _salesOrderId, SalesOrder_UpdateInput_Data _data, CancellationToken token = default);

        ///<summary>
        /// Deletes the specified Sales Order object.
        ///</summary>
        Task<Output> DeleteAsync(int _salesOrderId, CancellationToken token = default);

        ///<summary>
        /// Reads a list of Sales Order objects based on the specified criteria.
        ///</summary>
        Task<Output<ICollection<SalesOrder_ReadListOutput>>> ReadListAsync(SalesOrder_ReadListInput_Criteria _criteria, CancellationToken token = default);

        ///<summary>
        /// Reads the values of a Sales Order Detail object by its key.
        ///</summary>
        Task<Output<SalesOrderDetail_ReadOutput>> Detail_ReadAsync(int _salesOrderDetailId, CancellationToken token = default);

        ///<summary>
        /// Creates a new Sales Order Detail object using the specified data.
        ///</summary>
        Task<Output<SalesOrderDetail_CreateOutput>> Detail_CreateAsync(int _salesOrderId, SalesOrderDetail_CreateInput_Data _data, CancellationToken token = default);

        ///<summary>
        /// Updates existing Sales Order Detail object using the specified data.
        ///</summary>
        Task<Output> Detail_UpdateAsync(int _salesOrderDetailId, SalesOrderDetail_UpdateInput_Data _data, CancellationToken token = default);

        ///<summary>
        /// Deletes the specified Sales Order Detail object.
        ///</summary>
        Task<Output> Detail_DeleteAsync(int _salesOrderDetailId, CancellationToken token = default);

        ///<summary>
        /// Reads a list of Sales Order Detail objects based on the specified criteria.
        ///</summary>
        Task<Output<ICollection<SalesOrderDetail_ReadListOutput>>> Detail_ReadListAsync(int _salesOrderId, CancellationToken token = default);

        ///<summary>
        /// Reads the values of a Sales Order Reason object by its key.
        ///</summary>
        Task<Output<SalesOrderReason_ReadOutput>> Reason_ReadAsync(int _salesOrderId, int _salesReasonId, CancellationToken token = default);

        ///<summary>
        /// Creates a new Sales Order Reason object using the specified data.
        ///</summary>
        Task<Output> Reason_CreateAsync(int _salesOrderId, int _salesReasonId, SalesOrderReason_CreateInput_Data _data, CancellationToken token = default);

        ///<summary>
        /// Updates existing or creates a new Sales Order Reason object using the specified data.
        ///</summary>
        Task<Output> Reason_UpdateAsync(int _salesOrderId, int _salesReasonId, SalesOrderReason_UpdateInput_Data _data, CancellationToken token = default);

        ///<summary>
        /// Deletes the specified Sales Order Reason object.
        ///</summary>
        Task<Output> Reason_DeleteAsync(int _salesOrderId, int _salesReasonId, CancellationToken token = default);

        ///<summary>
        /// Reads a list of Sales Order Reason objects based on the specified criteria.
        ///</summary>
        Task<Output<ICollection<SalesOrderReason_ReadListOutput>>> Reason_ReadListAsync(int _salesOrderId, CancellationToken token = default);

    }
    #endregion

    #region SalesOrder_ReadOutput structure

    ///<summary>
    /// The output structure of operation ISalesOrderService.ReadAsync.
    ///</summary>
    public class SalesOrder_ReadOutput
    {
        
        ///<summary>
        /// Incremental number to track changes to the sales order over time.
        ///</summary>
        public byte RevisionNumber { get; set; }
        
        ///<summary>
        /// Dates the sales order was created.
        ///</summary>
        public DateTime OrderDate { get; set; }
        
        ///<summary>
        /// Date the order is due to the customer.
        ///</summary>
        public DateTime DueDate { get; set; }
        
        ///<summary>
        /// Date the order was shipped to the customer.
        ///</summary>
        public DateTime? ShipDate { get; set; }
        
        ///<summary>
        /// Order current status. 1 = In process; 2 = Approved; 3 = Backordered; 4 = Rejected; 5 = Shipped; 6 = Cancelled
        ///</summary>
        public byte Status { get; set; }
        
        ///<summary>
        /// 0 = Order placed by sales person. 1 = Order placed online by customer.
        ///</summary>
        public bool OnlineOrderFlag { get; set; }
        
        ///<summary>
        /// Unique sales order identification number.
        ///</summary>
        public string SalesOrderNumber { get; set; }
        
        ///<summary>
        /// Customer purchase order number reference. 
        ///</summary>
        public string PurchaseOrderNumber { get; set; }
        
        ///<summary>
        /// Financial accounting number reference.
        ///</summary>
        public string AccountNumber { get; set; }
        
        ///<summary>
        /// Customer identification number. Foreign key to Customer.BusinessEntityID.
        ///</summary>
        public int CustomerId { get; set; }
        
        ///<summary>
        /// Sales person who created the sales order. Foreign key to SalesPerson.BusinessEntityID.
        ///</summary>
        public int? SalesPersonId { get; set; }
        
        ///<summary>
        /// Territory in which the sale was made. Foreign key to SalesTerritory.SalesTerritoryID.
        ///</summary>
        public int? TerritoryId { get; set; }
        
        ///<summary>
        /// Customer billing address. Foreign key to Address.AddressID.
        ///</summary>
        public int BillToAddressId { get; set; }
        
        ///<summary>
        /// Customer shipping address. Foreign key to Address.AddressID.
        ///</summary>
        public int ShipToAddressId { get; set; }
        
        ///<summary>
        /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
        ///</summary>
        public int ShipMethodId { get; set; }
        
        ///<summary>
        /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
        ///</summary>
        public int? CreditCardId { get; set; }
        
        ///<summary>
        /// Approval code provided by the credit card company.
        ///</summary>
        public string CreditCardApprovalCode { get; set; }
        
        ///<summary>
        /// Currency exchange rate used. Foreign key to CurrencyRate.CurrencyRateID.
        ///</summary>
        public int? CurrencyRateId { get; set; }
        
        ///<summary>
        /// Sales subtotal. Computed as SUM(SalesOrderDetail.LineTotal)for the appropriate SalesOrderID.
        ///</summary>
        public decimal SubTotal { get; set; }
        
        ///<summary>
        /// Tax amount.
        ///</summary>
        public decimal TaxAmt { get; set; }
        
        ///<summary>
        /// Shipping cost.
        ///</summary>
        public decimal Freight { get; set; }
        
        ///<summary>
        /// Total due from customer. Computed as Subtotal + TaxAmt + Freight.
        ///</summary>
        public decimal TotalDue { get; set; }
        
        ///<summary>
        /// Sales representative comments.
        ///</summary>
        public string Comment { get; set; }
        
        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid Rowguid { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrder_CreateInput structure

    ///<summary>
    /// The input structure of operation ISalesOrderService.CreateAsync.
    ///</summary>
    public class SalesOrder_CreateInput
    {
        
        ///<summary>
        /// Incremental number to track changes to the sales order over time.
        ///</summary>
        [XRequired]
        public byte RevisionNumber { get; set; }
        
        ///<summary>
        /// Dates the sales order was created.
        ///</summary>
        [XRequired]
        public DateTime OrderDate { get; set; }
        
        ///<summary>
        /// Date the order is due to the customer.
        ///</summary>
        [XRequired]
        public DateTime DueDate { get; set; }
        
        ///<summary>
        /// Date the order was shipped to the customer.
        ///</summary>
        public DateTime? ShipDate { get; set; }
        
        ///<summary>
        /// Order current status. 1 = In process; 2 = Approved; 3 = Backordered; 4 = Rejected; 5 = Shipped; 6 = Cancelled
        ///</summary>
        [XRequired]
        public byte Status { get; set; }
        
        ///<summary>
        /// 0 = Order placed by sales person. 1 = Order placed online by customer.
        ///</summary>
        [XRequired]
        public bool OnlineOrderFlag { get; set; }
        
        ///<summary>
        /// Unique sales order identification number.
        ///</summary>
        [XRequired]
        [XMaxLength(25)]
        public string SalesOrderNumber { get; set; }
        
        ///<summary>
        /// Customer purchase order number reference. 
        ///</summary>
        [XMaxLength(25)]
        public string PurchaseOrderNumber { get; set; }
        
        ///<summary>
        /// Financial accounting number reference.
        ///</summary>
        [XMaxLength(15)]
        public string AccountNumber { get; set; }
        
        ///<summary>
        /// Customer identification number. Foreign key to Customer.BusinessEntityID.
        ///</summary>
        [XRequired]
        public int CustomerId { get; set; }
        
        ///<summary>
        /// Sales person who created the sales order. Foreign key to SalesPerson.BusinessEntityID.
        ///</summary>
        public int? SalesPersonId { get; set; }
        
        ///<summary>
        /// Territory in which the sale was made. Foreign key to SalesTerritory.SalesTerritoryID.
        ///</summary>
        public int? TerritoryId { get; set; }
        
        ///<summary>
        /// Customer billing address. Foreign key to Address.AddressID.
        ///</summary>
        [XRequired]
        public int BillToAddressId { get; set; }
        
        ///<summary>
        /// Customer shipping address. Foreign key to Address.AddressID.
        ///</summary>
        [XRequired]
        public int ShipToAddressId { get; set; }
        
        ///<summary>
        /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
        ///</summary>
        [XRequired]
        public int ShipMethodId { get; set; }
        
        ///<summary>
        /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
        ///</summary>
        public int? CreditCardId { get; set; }
        
        ///<summary>
        /// Approval code provided by the credit card company.
        ///</summary>
        [XMaxLength(15)]
        public string CreditCardApprovalCode { get; set; }
        
        ///<summary>
        /// Currency exchange rate used. Foreign key to CurrencyRate.CurrencyRateID.
        ///</summary>
        public int? CurrencyRateId { get; set; }
        
        ///<summary>
        /// Sales subtotal. Computed as SUM(SalesOrderDetail.LineTotal)for the appropriate SalesOrderID.
        ///</summary>
        [XRequired]
        public decimal SubTotal { get; set; }
        
        ///<summary>
        /// Tax amount.
        ///</summary>
        [XRequired]
        public decimal TaxAmt { get; set; }
        
        ///<summary>
        /// Shipping cost.
        ///</summary>
        [XRequired]
        public decimal Freight { get; set; }
        
        ///<summary>
        /// Total due from customer. Computed as Subtotal + TaxAmt + Freight.
        ///</summary>
        [XRequired]
        public decimal TotalDue { get; set; }
        
        ///<summary>
        /// Sales representative comments.
        ///</summary>
        [XMaxLength(128)]
        public string Comment { get; set; }
        
        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        [XRequired]
        public Guid Rowguid { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        [XRequired]
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrder_CreateOutput structure

    ///<summary>
    /// The output structure of operation ISalesOrderService.CreateAsync.
    ///</summary>
    public class SalesOrder_CreateOutput
    {
        
        public int SalesOrderId { get; set; }
    }
    #endregion

    #region SalesOrder_UpdateInput_Data structure

    ///<summary>
    /// Structure of parameter Data of the input structure of operation ISalesOrderService.UpdateAsync.
    ///</summary>
    public class SalesOrder_UpdateInput_Data
    {
        
        ///<summary>
        /// Incremental number to track changes to the sales order over time.
        ///</summary>
        [XRequired]
        public byte RevisionNumber { get; set; }
        
        ///<summary>
        /// Dates the sales order was created.
        ///</summary>
        [XRequired]
        public DateTime OrderDate { get; set; }
        
        ///<summary>
        /// Date the order is due to the customer.
        ///</summary>
        [XRequired]
        public DateTime DueDate { get; set; }
        
        ///<summary>
        /// Date the order was shipped to the customer.
        ///</summary>
        public DateTime? ShipDate { get; set; }
        
        ///<summary>
        /// Order current status. 1 = In process; 2 = Approved; 3 = Backordered; 4 = Rejected; 5 = Shipped; 6 = Cancelled
        ///</summary>
        [XRequired]
        public byte Status { get; set; }
        
        ///<summary>
        /// 0 = Order placed by sales person. 1 = Order placed online by customer.
        ///</summary>
        [XRequired]
        public bool OnlineOrderFlag { get; set; }
        
        ///<summary>
        /// Unique sales order identification number.
        ///</summary>
        [XRequired]
        [XMaxLength(25)]
        public string SalesOrderNumber { get; set; }
        
        ///<summary>
        /// Customer purchase order number reference. 
        ///</summary>
        [XMaxLength(25)]
        public string PurchaseOrderNumber { get; set; }
        
        ///<summary>
        /// Financial accounting number reference.
        ///</summary>
        [XMaxLength(15)]
        public string AccountNumber { get; set; }
        
        ///<summary>
        /// Customer identification number. Foreign key to Customer.BusinessEntityID.
        ///</summary>
        [XRequired]
        public int CustomerId { get; set; }
        
        ///<summary>
        /// Sales person who created the sales order. Foreign key to SalesPerson.BusinessEntityID.
        ///</summary>
        public int? SalesPersonId { get; set; }
        
        ///<summary>
        /// Territory in which the sale was made. Foreign key to SalesTerritory.SalesTerritoryID.
        ///</summary>
        public int? TerritoryId { get; set; }
        
        ///<summary>
        /// Customer billing address. Foreign key to Address.AddressID.
        ///</summary>
        [XRequired]
        public int BillToAddressId { get; set; }
        
        ///<summary>
        /// Customer shipping address. Foreign key to Address.AddressID.
        ///</summary>
        [XRequired]
        public int ShipToAddressId { get; set; }
        
        ///<summary>
        /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
        ///</summary>
        [XRequired]
        public int ShipMethodId { get; set; }
        
        ///<summary>
        /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
        ///</summary>
        public int? CreditCardId { get; set; }
        
        ///<summary>
        /// Approval code provided by the credit card company.
        ///</summary>
        [XMaxLength(15)]
        public string CreditCardApprovalCode { get; set; }
        
        ///<summary>
        /// Currency exchange rate used. Foreign key to CurrencyRate.CurrencyRateID.
        ///</summary>
        public int? CurrencyRateId { get; set; }
        
        ///<summary>
        /// Sales subtotal. Computed as SUM(SalesOrderDetail.LineTotal)for the appropriate SalesOrderID.
        ///</summary>
        [XRequired]
        public decimal SubTotal { get; set; }
        
        ///<summary>
        /// Tax amount.
        ///</summary>
        [XRequired]
        public decimal TaxAmt { get; set; }
        
        ///<summary>
        /// Shipping cost.
        ///</summary>
        [XRequired]
        public decimal Freight { get; set; }
        
        ///<summary>
        /// Total due from customer. Computed as Subtotal + TaxAmt + Freight.
        ///</summary>
        [XRequired]
        public decimal TotalDue { get; set; }
        
        ///<summary>
        /// Sales representative comments.
        ///</summary>
        [XMaxLength(128)]
        public string Comment { get; set; }
        
        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        [XRequired]
        public Guid Rowguid { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        [XRequired]
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrder_ReadListInput_Criteria structure

    ///<summary>
    /// Structure of parameter Criteria of the input structure of operation ISalesOrderService.ReadListAsync.
    ///</summary>
    public class SalesOrder_ReadListInput_Criteria
    {
        
        ///<summary>
        /// Comparison operator for the corresponding Revision Number criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string RevisionNumberOperator { get; set; }
        
        ///<summary>
        /// Incremental number to track changes to the sales order over time.
        ///</summary>
        public byte? RevisionNumber { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Revision Number criteria for the BETWEEN operator.
        ///</summary>
        public byte? RevisionNumber2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Order Date criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string OrderDateOperator { get; set; }
        
        ///<summary>
        /// Dates the sales order was created.
        ///</summary>
        public DateTime? OrderDate { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Order Date criteria for the BETWEEN operator.
        ///</summary>
        public DateTime? OrderDate2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Due Date criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string DueDateOperator { get; set; }
        
        ///<summary>
        /// Date the order is due to the customer.
        ///</summary>
        public DateTime? DueDate { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Due Date criteria for the BETWEEN operator.
        ///</summary>
        public DateTime? DueDate2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Ship Date criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string ShipDateOperator { get; set; }
        
        ///<summary>
        /// Date the order was shipped to the customer.
        ///</summary>
        public DateTime? ShipDate { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Ship Date criteria for the BETWEEN operator.
        ///</summary>
        public DateTime? ShipDate2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Status criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string StatusOperator { get; set; }
        
        ///<summary>
        /// Order current status. 1 = In process; 2 = Approved; 3 = Backordered; 4 = Rejected; 5 = Shipped; 6 = Cancelled
        ///</summary>
        public byte? Status { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Status criteria for the BETWEEN operator.
        ///</summary>
        public byte? Status2 { get; set; }
        
        ///<summary>
        /// 0 = Order placed by sales person. 1 = Order placed online by customer.
        ///</summary>
        public bool? OnlineOrderFlag { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Sales Order Number criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string SalesOrderNumberOperator { get; set; }
        
        ///<summary>
        /// Unique sales order identification number.
        ///</summary>
        [XMaxLength(25)]
        public string SalesOrderNumber { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Purchase Order Number criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string PurchaseOrderNumberOperator { get; set; }
        
        ///<summary>
        /// Customer purchase order number reference. 
        ///</summary>
        [XMaxLength(25)]
        public string PurchaseOrderNumber { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Account Number criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string AccountNumberOperator { get; set; }
        
        ///<summary>
        /// Financial accounting number reference.
        ///</summary>
        [XMaxLength(15)]
        public string AccountNumber { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Customer Id criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string CustomerIdOperator { get; set; }
        
        ///<summary>
        /// Customer identification number. Foreign key to Customer.BusinessEntityID.
        ///</summary>
        public int? CustomerId { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Customer Id criteria for the BETWEEN operator.
        ///</summary>
        public int? CustomerId2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Sales Person Id criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string SalesPersonIdOperator { get; set; }
        
        ///<summary>
        /// Sales person who created the sales order. Foreign key to SalesPerson.BusinessEntityID.
        ///</summary>
        public int? SalesPersonId { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Sales Person Id criteria for the BETWEEN operator.
        ///</summary>
        public int? SalesPersonId2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Territory Id criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string TerritoryIdOperator { get; set; }
        
        ///<summary>
        /// Territory in which the sale was made. Foreign key to SalesTerritory.SalesTerritoryID.
        ///</summary>
        public int? TerritoryId { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Territory Id criteria for the BETWEEN operator.
        ///</summary>
        public int? TerritoryId2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Bill To Address Id criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string BillToAddressIdOperator { get; set; }
        
        ///<summary>
        /// Customer billing address. Foreign key to Address.AddressID.
        ///</summary>
        public int? BillToAddressId { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Bill To Address Id criteria for the BETWEEN operator.
        ///</summary>
        public int? BillToAddressId2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Ship To Address Id criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string ShipToAddressIdOperator { get; set; }
        
        ///<summary>
        /// Customer shipping address. Foreign key to Address.AddressID.
        ///</summary>
        public int? ShipToAddressId { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Ship To Address Id criteria for the BETWEEN operator.
        ///</summary>
        public int? ShipToAddressId2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Ship Method Id criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string ShipMethodIdOperator { get; set; }
        
        ///<summary>
        /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
        ///</summary>
        public int? ShipMethodId { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Ship Method Id criteria for the BETWEEN operator.
        ///</summary>
        public int? ShipMethodId2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Credit Card Id criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string CreditCardIdOperator { get; set; }
        
        ///<summary>
        /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
        ///</summary>
        public int? CreditCardId { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Credit Card Id criteria for the BETWEEN operator.
        ///</summary>
        public int? CreditCardId2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Credit Card Approval Code criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string CreditCardApprovalCodeOperator { get; set; }
        
        ///<summary>
        /// Approval code provided by the credit card company.
        ///</summary>
        [XMaxLength(15)]
        public string CreditCardApprovalCode { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Currency Rate Id criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string CurrencyRateIdOperator { get; set; }
        
        ///<summary>
        /// Currency exchange rate used. Foreign key to CurrencyRate.CurrencyRateID.
        ///</summary>
        public int? CurrencyRateId { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Currency Rate Id criteria for the BETWEEN operator.
        ///</summary>
        public int? CurrencyRateId2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Sub Total criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string SubTotalOperator { get; set; }
        
        ///<summary>
        /// Sales subtotal. Computed as SUM(SalesOrderDetail.LineTotal)for the appropriate SalesOrderID.
        ///</summary>
        public decimal? SubTotal { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Sub Total criteria for the BETWEEN operator.
        ///</summary>
        public decimal? SubTotal2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Tax Amt criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string TaxAmtOperator { get; set; }
        
        ///<summary>
        /// Tax amount.
        ///</summary>
        public decimal? TaxAmt { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Tax Amt criteria for the BETWEEN operator.
        ///</summary>
        public decimal? TaxAmt2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Freight criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string FreightOperator { get; set; }
        
        ///<summary>
        /// Shipping cost.
        ///</summary>
        public decimal? Freight { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Freight criteria for the BETWEEN operator.
        ///</summary>
        public decimal? Freight2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Total Due criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string TotalDueOperator { get; set; }
        
        ///<summary>
        /// Total due from customer. Computed as Subtotal + TaxAmt + Freight.
        ///</summary>
        public decimal? TotalDue { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Total Due criteria for the BETWEEN operator.
        ///</summary>
        public decimal? TotalDue2 { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Comment criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string CommentOperator { get; set; }
        
        ///<summary>
        /// Sales representative comments.
        ///</summary>
        [XMaxLength(128)]
        public string Comment { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Rowguid criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string RowguidOperator { get; set; }
        
        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid? Rowguid { get; set; }
        
        ///<summary>
        /// Comparison operator for the corresponding Modified Date criteria.
        ///</summary>
        [XMaxLength(25)]
        [XLookupValue(Operators.EnumName)]
        public string ModifiedDateOperator { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime? ModifiedDate { get; set; }
        
        ///<summary>
        /// End of range for the corresponding Modified Date criteria for the BETWEEN operator.
        ///</summary>
        public DateTime? ModifiedDate2 { get; set; }
    }
    #endregion

    #region SalesOrder_ReadListOutput structure

    ///<summary>
    /// The output structure of operation ISalesOrderService.ReadListAsync.
    ///</summary>
    public class SalesOrder_ReadListOutput
    {
        
        public int SalesOrderId { get; set; }
        
        ///<summary>
        /// Incremental number to track changes to the sales order over time.
        ///</summary>
        public byte RevisionNumber { get; set; }
        
        ///<summary>
        /// Dates the sales order was created.
        ///</summary>
        public DateTime OrderDate { get; set; }
        
        ///<summary>
        /// Date the order is due to the customer.
        ///</summary>
        public DateTime DueDate { get; set; }
        
        ///<summary>
        /// Date the order was shipped to the customer.
        ///</summary>
        public DateTime? ShipDate { get; set; }
        
        ///<summary>
        /// Order current status. 1 = In process; 2 = Approved; 3 = Backordered; 4 = Rejected; 5 = Shipped; 6 = Cancelled
        ///</summary>
        public byte Status { get; set; }
        
        ///<summary>
        /// 0 = Order placed by sales person. 1 = Order placed online by customer.
        ///</summary>
        public bool OnlineOrderFlag { get; set; }
        
        ///<summary>
        /// Unique sales order identification number.
        ///</summary>
        public string SalesOrderNumber { get; set; }
        
        ///<summary>
        /// Customer purchase order number reference. 
        ///</summary>
        public string PurchaseOrderNumber { get; set; }
        
        ///<summary>
        /// Financial accounting number reference.
        ///</summary>
        public string AccountNumber { get; set; }
        
        ///<summary>
        /// Customer identification number. Foreign key to Customer.BusinessEntityID.
        ///</summary>
        public int CustomerId { get; set; }
        
        ///<summary>
        /// Sales person who created the sales order. Foreign key to SalesPerson.BusinessEntityID.
        ///</summary>
        public int? SalesPersonId { get; set; }
        
        ///<summary>
        /// Territory in which the sale was made. Foreign key to SalesTerritory.SalesTerritoryID.
        ///</summary>
        public int? TerritoryId { get; set; }
        
        ///<summary>
        /// Customer billing address. Foreign key to Address.AddressID.
        ///</summary>
        public int BillToAddressId { get; set; }
        
        ///<summary>
        /// Customer shipping address. Foreign key to Address.AddressID.
        ///</summary>
        public int ShipToAddressId { get; set; }
        
        ///<summary>
        /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
        ///</summary>
        public int ShipMethodId { get; set; }
        
        ///<summary>
        /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
        ///</summary>
        public int? CreditCardId { get; set; }
        
        ///<summary>
        /// Approval code provided by the credit card company.
        ///</summary>
        public string CreditCardApprovalCode { get; set; }
        
        ///<summary>
        /// Currency exchange rate used. Foreign key to CurrencyRate.CurrencyRateID.
        ///</summary>
        public int? CurrencyRateId { get; set; }
        
        ///<summary>
        /// Sales subtotal. Computed as SUM(SalesOrderDetail.LineTotal)for the appropriate SalesOrderID.
        ///</summary>
        public decimal SubTotal { get; set; }
        
        ///<summary>
        /// Tax amount.
        ///</summary>
        public decimal TaxAmt { get; set; }
        
        ///<summary>
        /// Shipping cost.
        ///</summary>
        public decimal Freight { get; set; }
        
        ///<summary>
        /// Total due from customer. Computed as Subtotal + TaxAmt + Freight.
        ///</summary>
        public decimal TotalDue { get; set; }
        
        ///<summary>
        /// Sales representative comments.
        ///</summary>
        public string Comment { get; set; }
        
        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid Rowguid { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrderDetail_ReadOutput structure

    ///<summary>
    /// The output structure of operation IDetailService.Detail_ReadAsync.
    ///</summary>
    public class SalesOrderDetail_ReadOutput
    {
        
        public int SalesOrderId { get; set; }
        
        ///<summary>
        /// Shipment tracking number supplied by the shipper.
        ///</summary>
        public string CarrierTrackingNumber { get; set; }
        
        ///<summary>
        /// Quantity ordered per product.
        ///</summary>
        public short OrderQty { get; set; }
        
        public int SpecialOfferId { get; set; }
        
        public int ProductId { get; set; }
        
        ///<summary>
        /// Selling price of a single product.
        ///</summary>
        public decimal UnitPrice { get; set; }
        
        ///<summary>
        /// Discount amount.
        ///</summary>
        public decimal UnitPriceDiscount { get; set; }
        
        ///<summary>
        /// Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.
        ///</summary>
        public decimal LineTotal { get; set; }
        
        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid Rowguid { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrderDetail_CreateInput_Data structure

    ///<summary>
    /// Structure of parameter Data of the input structure of operation IDetailService.Detail_CreateAsync.
    ///</summary>
    public class SalesOrderDetail_CreateInput_Data
    {
        
        ///<summary>
        /// Shipment tracking number supplied by the shipper.
        ///</summary>
        [XMaxLength(25)]
        public string CarrierTrackingNumber { get; set; }
        
        ///<summary>
        /// Quantity ordered per product.
        ///</summary>
        [XRequired]
        public short OrderQty { get; set; }
        
        [XRequired]
        public int SpecialOfferId { get; set; }
        
        [XRequired]
        public int ProductId { get; set; }
        
        ///<summary>
        /// Selling price of a single product.
        ///</summary>
        [XRequired]
        public decimal UnitPrice { get; set; }
        
        ///<summary>
        /// Discount amount.
        ///</summary>
        [XRequired]
        public decimal UnitPriceDiscount { get; set; }
        
        ///<summary>
        /// Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.
        ///</summary>
        [XRequired]
        public decimal LineTotal { get; set; }
        
        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        [XRequired]
        public Guid Rowguid { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        [XRequired]
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrderDetail_CreateOutput structure

    ///<summary>
    /// The output structure of operation IDetailService.Detail_CreateAsync.
    ///</summary>
    public class SalesOrderDetail_CreateOutput
    {
        
        public int SalesOrderDetailId { get; set; }
    }
    #endregion

    #region SalesOrderDetail_UpdateInput_Data structure

    ///<summary>
    /// Structure of parameter Data of the input structure of operation IDetailService.Detail_UpdateAsync.
    ///</summary>
    public class SalesOrderDetail_UpdateInput_Data
    {
        
        ///<summary>
        /// Shipment tracking number supplied by the shipper.
        ///</summary>
        [XMaxLength(25)]
        public string CarrierTrackingNumber { get; set; }
        
        ///<summary>
        /// Quantity ordered per product.
        ///</summary>
        [XRequired]
        public short OrderQty { get; set; }
        
        [XRequired]
        public int SpecialOfferId { get; set; }
        
        [XRequired]
        public int ProductId { get; set; }
        
        ///<summary>
        /// Selling price of a single product.
        ///</summary>
        [XRequired]
        public decimal UnitPrice { get; set; }
        
        ///<summary>
        /// Discount amount.
        ///</summary>
        [XRequired]
        public decimal UnitPriceDiscount { get; set; }
        
        ///<summary>
        /// Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.
        ///</summary>
        [XRequired]
        public decimal LineTotal { get; set; }
        
        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        [XRequired]
        public Guid Rowguid { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        [XRequired]
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrderDetail_ReadListOutput structure

    ///<summary>
    /// The output structure of operation IDetailService.Detail_ReadListAsync.
    ///</summary>
    public class SalesOrderDetail_ReadListOutput
    {
        
        public int SalesOrderDetailId { get; set; }
        
        ///<summary>
        /// Shipment tracking number supplied by the shipper.
        ///</summary>
        public string CarrierTrackingNumber { get; set; }
        
        ///<summary>
        /// Quantity ordered per product.
        ///</summary>
        public short OrderQty { get; set; }
        
        public int SpecialOfferId { get; set; }
        
        public int ProductId { get; set; }
        
        ///<summary>
        /// Selling price of a single product.
        ///</summary>
        public decimal UnitPrice { get; set; }
        
        ///<summary>
        /// Discount amount.
        ///</summary>
        public decimal UnitPriceDiscount { get; set; }
        
        ///<summary>
        /// Per product subtotal. Computed as UnitPrice * (1 - UnitPriceDiscount) * OrderQty.
        ///</summary>
        public decimal LineTotal { get; set; }
        
        ///<summary>
        /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
        ///</summary>
        public Guid Rowguid { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrderReason_ReadOutput structure

    ///<summary>
    /// The output structure of operation IReasonService.Reason_ReadAsync.
    ///</summary>
    public class SalesOrderReason_ReadOutput
    {
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrderReason_CreateInput_Data structure

    ///<summary>
    /// Structure of parameter Data of the input structure of operation IReasonService.Reason_CreateAsync.
    ///</summary>
    public class SalesOrderReason_CreateInput_Data
    {
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        [XRequired]
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrderReason_UpdateInput_Data structure

    ///<summary>
    /// Structure of parameter Data of the input structure of operation IReasonService.Reason_UpdateAsync.
    ///</summary>
    public class SalesOrderReason_UpdateInput_Data
    {
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        [XRequired]
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

    #region SalesOrderReason_ReadListOutput structure

    ///<summary>
    /// The output structure of operation IReasonService.Reason_ReadListAsync.
    ///</summary>
    public class SalesOrderReason_ReadListOutput
    {
        
        public int SalesReasonId { get; set; }
        
        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        public DateTime ModifiedDate { get; set; }
    }
    #endregion

}