//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    #region ISalesTerritoryService interface

    ///<summary>
    /// Sales territory lookup table.
    ///</summary>
    public interface ISalesTerritoryService
    {

        ///<summary>
        /// Reads a list of Sales Territory objects based on the specified criteria.
        ///</summary>
        Task<Output<ICollection<SalesTerritory_ReadListOutput>>> ReadListAsync(CancellationToken token = default);

    }
    #endregion

    #region SalesTerritory_ReadListOutput structure

    ///<summary>
    /// The output structure of operation ISalesTerritoryService.ReadListAsync.
    ///</summary>
    public class SalesTerritory_ReadListOutput
    {
        
        public int TerritoryId { get; set; }
        
        ///<summary>
        /// Sales territory description
        ///</summary>
        public string Name { get; set; }
        
        ///<summary>
        /// ISO standard country or region code. Foreign key to CountryRegion.CountryRegionCode. 
        ///</summary>
        public string CountryRegionCode { get; set; }
        
        ///<summary>
        /// Geographic area to which the sales territory belong.
        ///</summary>
        public string Group { get; set; }
    }
    #endregion

}