//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    #region ISalesPersonService interface

    ///<summary>
    /// Sales representative current information.
    ///</summary>
    public interface ISalesPersonService
    {

        ///<summary>
        /// Reads a list of Sales Person objects based on the specified criteria.
        ///</summary>
        Task<Output<ICollection<SalesPerson_ReadListOutput>>> ReadListAsync(CancellationToken token = default);

    }
    #endregion

    #region SalesPerson_ReadListOutput structure

    ///<summary>
    /// The output structure of operation ISalesPersonService.ReadListAsync.
    ///</summary>
    public class SalesPerson_ReadListOutput
    {
        
        public int BusinessEntityId { get; set; }
        
        ///<summary>
        /// Territory currently assigned to. Foreign key to SalesTerritory.SalesTerritoryID.
        ///</summary>
        public int? TerritoryId { get; set; }
        
        public string Name { get; set; }
        
        public bool IsCurrent { get; set; }
    }
    #endregion

}