//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Xomega.Framework.Services;

namespace AdventureWorks.Services.Common
{
    #region ISpecialOfferService interface

    ///<summary>
    /// Sale discounts lookup table.
    ///</summary>
    public interface ISpecialOfferService
    {

        ///<summary>
        /// Reads a list of Special Offer objects based on the specified criteria.
        ///</summary>
        Task<Output<ICollection<SpecialOffer_ReadListOutput>>> ReadListAsync(CancellationToken token = default);

    }
    #endregion

    #region SpecialOffer_ReadListOutput structure

    ///<summary>
    /// The output structure of operation ISpecialOfferService.ReadListAsync.
    ///</summary>
    public class SpecialOffer_ReadListOutput
    {
        
        public int SpecialOfferId { get; set; }
        
        ///<summary>
        /// Discount description.
        ///</summary>
        public string Description { get; set; }
        
        public bool IsActive { get; set; }
        
        ///<summary>
        /// Group the discount applies to such as Reseller or Customer.
        ///</summary>
        public string Category { get; set; }
    }
    #endregion

}