//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Service Contracts" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;

namespace AdventureWorks.Services.Common
{
    #region PaymentInfo structure

    public class PaymentInfo
    {
        
        ///<summary>
        /// Sales subtotal. Computed as SUM(SalesOrderDetail.LineTotal)for the appropriate SalesOrderID.
        ///</summary>
        public decimal SubTotal { get; set; }
        
        ///<summary>
        /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
        ///</summary>
        public int ShipMethodId { get; set; }
        
        ///<summary>
        /// Tax amount.
        ///</summary>
        public decimal TaxAmt { get; set; }
        
        ///<summary>
        /// Shipping cost.
        ///</summary>
        public decimal Freight { get; set; }
        
        ///<summary>
        /// Total due from customer. Computed as Subtotal + TaxAmt + Freight.
        ///</summary>
        public decimal TotalDue { get; set; }
        
        ///<summary>
        /// Date the order is due to the customer.
        ///</summary>
        public DateTime DueDate { get; set; }
        
        public string CurrencyRate { get; set; }
        
        ///<summary>
        /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
        ///</summary>
        public int? CreditCardId { get; set; }
        
        ///<summary>
        /// Approval code provided by the credit card company.
        ///</summary>
        public string CreditCardApprovalCode { get; set; }
    }
    #endregion

    #region PaymentUpdate structure

    public class PaymentUpdate
    {
        
        ///<summary>
        /// Shipping method. Foreign key to ShipMethod.ShipMethodID.
        ///</summary>
        public int ShipMethodId { get; set; }
        
        ///<summary>
        /// Date the order is due to the customer.
        ///</summary>
        public DateTime DueDate { get; set; }
        
        ///<summary>
        /// Credit card identification number. Foreign key to CreditCard.CreditCardID.
        ///</summary>
        public int? CreditCardId { get; set; }
        
        ///<summary>
        /// Approval code provided by the credit card company.
        ///</summary>
        public string CreditCardApprovalCode { get; set; }
    }
    #endregion

}