//---------------------------------------------------------------------------------------------
// This file was AUTO-GENERATED by "Xomega Data Objects" Xomega.Net generator.
//
// Manual CHANGES to this file WILL BE LOST when the code is regenerated.
//---------------------------------------------------------------------------------------------

using System;
using Xomega.Framework;
using Xomega.Framework.Properties;

namespace AdventureWorks.Client.Common.DataObjects
{
    public partial class SalesOrderCustomerObject : DataObject
    {
        #region Constants

        public const string AccountNumber = "AccountNumber";
        public const string BillToAddressId = "BillToAddressId";
        public const string CustomerId = "CustomerId";
        public const string PersonId = "PersonId";
        public const string PersonName = "PersonName";
        public const string ShipToAddressId = "ShipToAddressId";
        public const string StoreId = "StoreId";
        public const string StoreName = "StoreName";
        public const string TerritoryId = "TerritoryId";

        #endregion

        #region Properties

        public TextProperty AccountNumberProperty { get; private set; }
        public IntegerKeyProperty BillToAddressIdProperty { get; private set; }
        public IntegerKeyProperty CustomerIdProperty { get; private set; }
        public IntegerKeyProperty PersonIdProperty { get; private set; }
        public TextProperty PersonNameProperty { get; private set; }
        public IntegerKeyProperty ShipToAddressIdProperty { get; private set; }
        public IntegerKeyProperty StoreIdProperty { get; private set; }
        public TextProperty StoreNameProperty { get; private set; }
        public EnumIntProperty TerritoryIdProperty { get; private set; }

        #endregion

        #region Construction

        public SalesOrderCustomerObject()
        {
        }

        public SalesOrderCustomerObject(IServiceProvider serviceProvider) : base(serviceProvider)
        {
        }

        protected override void Initialize()
        {
            CustomerIdProperty = new IntegerKeyProperty(this, CustomerId)
            {
                Required = true,
                IsKey = true,
            };
            StoreIdProperty = new IntegerKeyProperty(this, StoreId)
            {
                Editable = false,
            };
            StoreNameProperty = new TextProperty(this, StoreName)
            {
                Editable = false,
            };
            PersonIdProperty = new IntegerKeyProperty(this, PersonId)
            {
                Editable = false,
            };
            PersonNameProperty = new TextProperty(this, PersonName)
            {
                Editable = false,
            };
            AccountNumberProperty = new TextProperty(this, AccountNumber)
            {
                Required = true,
                Size = 10,
                Editable = false,
            };
            TerritoryIdProperty = new EnumIntProperty(this, TerritoryId)
            {
                EnumType = "sales territory",
                Editable = false,
            };
            BillToAddressIdProperty = new IntegerKeyProperty(this, BillToAddressId)
            {
            };
            ShipToAddressIdProperty = new IntegerKeyProperty(this, ShipToAddressId)
            {
            };
        }

        #endregion
    }
}